server:
  port: 8082
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=attendanceSystem
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: lijingwen
    password: ljw+545464
  jpa:
    database: sql_server
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect