server:
  port: 8081
#  配置前缀
#  servlet:
#    context-path: /girl
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?useUnicode=ture&characterEncoding=utf8&useSSL=false
    username: root
    password: root
